# CONFIGURAÇÕES DO CONSUMER PROCESSING - Porta do servidor HTTP
server.port=8081

# Nome da aplicação
spring.application.name=consumer-processing

# CONFIGURAÇÕES DO KAFKA BROKER - Endereço do broker Kafka
spring.kafka.bootstrap-servers=localhost:9092

# CONFIGURAÇÕES DO CONSUMER - ID do grupo de consumidores
spring.kafka.consumer.group-id=order-processing-group

# Comportamento quando não há offset salvo
# (earliest = início, latest = novas mensagens)
spring.kafka.consumer.auto-offset-reset=earliest

# CONFIGURAÇÕES DE DESSERIALIZAÇÃO - Desserializador da chave (String)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Desserializador do valor (JSON)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# CONFIGURAÇÕES DO JACKSON JSON - Pacotes confiáveis para desserialização (segurança)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kafkaorder.consumer_processing.event

# Classe padrão para desserialização do JSON
spring.kafka.consumer.properties.spring.json.value.default.type=com.kafkaorder.consumer_processing.event.OrderCreatedEvent