# CONFIGURAÇÕES DO PRODUCER KAFKA - Nome da aplicação
spring.application.name=producer

# CONFIGURAÇÕES DO TOPIC - Nome do tópico Kafka
app.kafka.topics.orders-created=orders.created

# CONFIGURAÇÕES DO KAFKA BROKER - Endereço do broker Kafka
spring.kafka.bootstrap-servers=localhost:9092

#REMOVIDOS POIS JA ESTA CONFIGURADOS NO KafkaConfig.java
# CONFIGURAÇÕES DE SERIALIZAÇÃO - Serializador da chave (String - orderId)
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Serializador do valor (JSON - OrderCreatedEvent)
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer